const KEY='cicadianai-job-list-v1';
const seed={users:[],projects:[],session:null};
// Some browsers block localStorage for a page opened directly from a file.
// Keep the app usable in that case instead of stopping before it can render.
const store={
  get(){try{return localStorage.getItem(KEY)}catch(_){return null}},
  set(value){try{localStorage.setItem(KEY,value)}catch(_){/* browser session only */}}
};
let db=JSON.parse(store.get()||'null')||seed;
const save=()=>store.set(JSON.stringify(db));
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n||0);
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const current=()=>db.users.find(u=>u.id===db.session?.id);
const projectTotal=p=>p.hours*p.rate;
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random()}
function render(){document.querySelector('#app').innerHTML=current()?appView():authView();bind();}
function authView(){return `<section class="auth"><div class="brand-panel"><div class="logo">cicadianai<span>·</span></div><div><p class="eyebrow">Work, clearly organised</p><h1>Make every project count.</h1><p>Assign work, collect proof, and keep payments easy to understand.</p></div><small>Built for hosts and their teams.</small></div><div class="auth-box"><div class="auth-card"><p class="eyebrow">Welcome</p><h2>Cicadianai job list</h2><p class="muted">Choose your workspace to get started.</p><div class="role-switch"><button class="role active" data-role="host">I’m a host</button><button class="role" data-role="user">I’m a worker</button></div><form id="auth-form"><label>Email</label><input required type="email" name="email" placeholder="you@example.com"><label>Password</label><input required minlength="4" type="password" name="password" placeholder="At least 4 characters"><button class="btn" type="submit">Create account</button></form><button id="signin" class="btn secondary" style="margin-top:.7rem">I already have an account</button><p class="auth-note">This demo stores accounts and work data in this browser. A production release should use secure server-side sign-in and file storage.</p><div id="auth-error" class="error"></div></div></div></section>`}
function appView(){let u=current(), host=u.role==='host', page=db.session.page||'projects';return `<section class="shell"><aside class="sidebar"><div class="logo">cicadianai<span>·</span></div><nav class="nav"><button data-page="projects" class="${page==='projects'?'active':''}">Projects</button>${host?'<button data-page="team" class="'+(page==='team'?'active':'')+'">Team</button>':''}<button data-page="ledger" class="${page==='ledger'?'active':''}">My earnings</button></nav><div class="account"><strong>${esc(u.name||u.email)}</strong><span>${host?'Host workspace':'Worker account'}</span><button id="logout" class="btn small secondary" style="margin-top:.7rem">Sign out</button></div></aside><main class="content">${page==='projects'?projectsPage(u,host):page==='ledger'?ledgerPage(u):teamPage()}</main></section><div id="modal-root"></div>`}
function pageHeading(title,sub,button=''){return `<header class="topbar"><div><p class="eyebrow">${current().role==='host'?'Host workspace':'Your workspace'}</p><h1>${title}</h1><p>${sub}</p></div>${button}</header>`}
function projectsPage(u,host){let ps=host?db.projects:db.projects.filter(p=>p.status==='open'&&(p.assignee==='any'||p.assignee===u.id)||p.worker===u.id);let open=ps.filter(p=>p.status==='open'), active=ps.filter(p=>p.status!=='open');let stats=host?[[db.projects.length,'Total projects'],[db.projects.filter(p=>p.status==='open').length,'Open to accept'],[db.projects.filter(p=>p.status==='submitted').length,'Ready to approve'],[db.projects.filter(p=>p.status==='approved').reduce((a,p)=>a+projectTotal(p),0),'Paid out']]:[[open.length,'Available'],[db.projects.filter(p=>p.worker===u.id&&p.status==='accepted').length,'In progress'],[db.projects.filter(p=>p.worker===u.id&&p.status==='submitted').length,'Under review'],[db.projects.filter(p=>p.worker===u.id&&p.status==='approved').reduce((a,p)=>a+projectTotal(p),0),'Earned']];return `${pageHeading(host?'Project control':'Find your next project',host?'Create assignments, follow delivery, and approve completed work.':'Accept an available project. Your active work is kept separate.',host?'<button class="btn" id="new-project">+ New project</button>':'')}<div class="stats">${stats.map(s=>`<article class="stat"><span class="eyebrow">${s[1]}</span><b>${typeof s[0]==='number'&&s[1].match(/Paid|Earned/)?money(s[0]):s[0]}</b></article>`).join('')}</div>${open.length?`<div class="section-head"><h2>${host?'Available projects':'Available to accept'}</h2></div><div class="project-list">${open.map(p=>projectCard(p,host,u)).join('')}</div>`:''}${active.length?`<div class="section-head"><h2>${host?'Assigned & completed':'Your active work'}</h2></div><div class="project-list">${active.map(p=>projectCard(p,host,u)).join('')}</div>`:''}${!ps.length?'<div class="empty">No projects here yet.</div>':''}`}
function projectCard(p,host,u){let status={open:'Open',accepted:'In progress',submitted:'Evidence submitted',approved:'Approved',cancelled:'Cancelled'}[p.status];let assignee=p.assignee==='any'?'Anyone may accept':esc(db.users.find(x=>x.id===p.assignee)?.name||'Selected worker');let worker=db.users.find(x=>x.id===p.worker);let buttons='';if(host&&p.status==='open')buttons=`<button class="btn small secondary" data-action="edit" data-id="${p.id}">Edit</button><button class="btn small danger" data-action="delete" data-id="${p.id}">Delete</button>`;if(!host&&p.status==='open')buttons=`<button class="btn small" data-action="accept" data-id="${p.id}">Accept project</button>`;if(!host&&p.worker===u.id&&['accepted','submitted'].includes(p.status))buttons=`<button class="btn small secondary" data-action="evidence" data-id="${p.id}">Add evidence</button><button class="btn small danger" data-action="cancel" data-id="${p.id}">Request cancellation</button>`;if(host&&p.status==='submitted')buttons=`<button class="btn small" data-action="approve" data-id="${p.id}">Approve & add to ledger</button>`;return `<article class="project"><div><h3>${esc(p.name)}</h3><p><span class="badge ${p.status==='submitted'||p.status==='approved'?'done':p.status==='accepted'?'assigned':''}">${status}</span>${p.hours} hours · ${money(p.rate)}/hour · <strong>${money(projectTotal(p))}</strong>${p.deadline?' · Due '+new Date(p.deadline+'T00:00:00').toLocaleDateString('en-GB'):''}</p><p style="margin-top:.35rem">${host?(worker?'Worker: '+esc(worker.name||worker.email):assignee):(p.worker?'Assigned to you':assignee)}</p>${p.evidence?.length?`<div class="evidence">${p.evidence.map(e=>`<img src="${e}" alt="Work evidence">`).join('')}</div>`:''}</div><div class="project-actions">${buttons}</div></article>`}
function ledgerPage(u){let approved=db.projects.filter(p=>p.worker===u.id&&p.status==='approved');let now=new Date(), month=approved.filter(p=>new Date(p.approvedAt).getMonth()===now.getMonth()&&new Date(p.approvedAt).getFullYear()===now.getFullYear()).reduce((a,p)=>a+projectTotal(p),0);let months=Array.from({length:12},(_,i)=>{let d=new Date(now.getFullYear(),i,1),sum=approved.filter(p=>{let x=new Date(p.approvedAt);return x.getMonth()===i&&x.getFullYear()===now.getFullYear()}).reduce((a,p)=>a+projectTotal(p),0);return {label:d.toLocaleString('en-GB',{month:'short'}),sum}}),max=Math.max(...months.map(m=>m.sum),1);return `${pageHeading('My earnings','Approved projects are added to your private ledger.')}<div class="stats"><article class="stat"><span class="eyebrow">This month</span><b>${money(month)}</b></article><article class="stat"><span class="eyebrow">Approved projects</span><b>${approved.length}</b></article><article class="stat"><span class="eyebrow">Average project</span><b>${money(approved.length?approved.reduce((a,p)=>a+projectTotal(p),0)/approved.length:0)}</b></article><article class="stat"><span class="eyebrow">Year total</span><b>${money(approved.reduce((a,p)=>a+projectTotal(p),0))}</b></article></div><div class="section-head"><h2>Monthly earnings · ${now.getFullYear()}</h2></div><div class="chart">${months.map(m=>`<div class="bar"><i style="height:${m.sum/max*170}px" title="${money(m.sum)}"></i>${m.label}</div>`).join('')}</div><div class="section-head"><h2>Payment ledger</h2></div><div class="ledger"><table><thead><tr><th>Project</th><th>Approved</th><th>Hours</th><th>Rate</th><th>Total</th></tr></thead><tbody>${approved.length?approved.map(p=>`<tr><td>${esc(p.name)}</td><td>${new Date(p.approvedAt).toLocaleDateString('en-GB')}</td><td>${p.hours}</td><td>${money(p.rate)}</td><td><strong>${money(projectTotal(p))}</strong></td></tr>`).join(''):'<tr><td colspan="5" class="muted">No approved payments yet.</td></tr>'}</tbody></table></div>`}
function teamPage(){let users=db.users.filter(u=>u.role==='user');return `${pageHeading('Your team','Choose a specific worker while setting up a project.')}<div class="project-list">${users.length?users.map(u=>`<article class="project"><div><h3>${esc(u.name||u.email)}</h3><p>${esc(u.email)} · Worker account</p></div></article>`).join(''):'<div class="empty">No workers have signed up yet. Ask them to create a Worker account.</div>'}</div>`}
function modal(html){document.querySelector('#modal-root').innerHTML=`<div class="modal-wrap"><section class="modal">${html}</section></div>`;document.querySelector('.modal-wrap').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.remove()})}
function projectForm(p={}){let workers=db.users.filter(u=>u.role==='user');modal(`<form id="project-form"><div class="section-head"><h2>${p.id?'Edit project':'New project'}</h2><button type="button" id="close-modal" class="btn small secondary">Close</button></div><div class="form-grid"><div class="full"><label>Project name</label><input required name="name" value="${esc(p.name)}" placeholder="e.g. Prepare September newsletter"></div><div><label>Hours required</label><input required min="0.5" step="0.5" type="number" name="hours" value="${p.hours||''}" placeholder="8"></div><div><label>Pay per hour (£)</label><input required min="0" step="0.01" type="number" name="rate" value="${p.rate||''}" placeholder="20"></div><div><label>Deadline (optional)</label><input type="date" name="deadline" value="${p.deadline||''}"></div><div><label>Assign to</label><select name="assignee"><option value="any" ${p.assignee==='any'?'selected':''}>Anyone can accept</option>${workers.map(u=>`<option value="${u.id}" ${p.assignee===u.id?'selected':''}>${esc(u.name||u.email)}</option>`).join('')}</select></div><div class="full details">Estimated project cost: <strong id="cost-preview">${money(projectTotal({hours:p.hours||0,rate:p.rate||0}))}</strong></div></div><div class="form-actions"><button class="btn" type="submit">${p.id?'Save changes':'Create project'}</button></div></form>`);document.querySelector('#close-modal').onclick=()=>document.querySelector('.modal-wrap').remove();let f=document.querySelector('#project-form');f.hours.oninput=f.rate.oninput=()=>document.querySelector('#cost-preview').textContent=money(Number(f.hours.value)*Number(f.rate.value));f.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(f));if(p.id){Object.assign(p,{...x,hours:+x.hours,rate:+x.rate})}else db.projects.unshift({id:uid(),...x,hours:+x.hours,rate:+x.rate,status:'open',evidence:[]});save();render()}}
function bind(){let app=document.querySelector('#app');if(!current()){let role='host';document.querySelectorAll('.role').forEach(b=>b.onclick=()=>{role=b.dataset.role;document.querySelectorAll('.role').forEach(x=>x.classList.toggle('active',x===b))});let signin=false;document.querySelector('#signin').onclick=()=>{signin=!signin;document.querySelector('#signin').textContent=signin?'Create a new account':'I already have an account';document.querySelector('#auth-form button').textContent=signin?'Sign in':'Create account'};document.querySelector('#auth-form').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),found=db.users.find(u=>u.email.toLowerCase()===f.email.toLowerCase()&&u.role===role);let er=document.querySelector('#auth-error');if(signin){if(!found||found.password!==f.password){er.textContent='Email, password, or account type is incorrect.';return}db.session={id:found.id,page:'projects'}}else{if(db.users.some(u=>u.email.toLowerCase()===f.email.toLowerCase()&&u.role===role)){er.textContent='This account already exists. Choose “I already have an account”.';return}let u={id:uid(),email:f.email,password:f.password,role,name:f.email.split('@')[0]};db.users.push(u);db.session={id:u.id,page:'projects'}}save();render()};return}document.querySelector('#logout').onclick=()=>{db.session=null;save();render()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{db.session.page=b.dataset.page;save();render()});document.querySelector('#new-project')?.addEventListener('click',()=>projectForm());document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));}
function action(type,id){let p=db.projects.find(p=>p.id===id),u=current();if(type==='edit')return projectForm(p);if(type==='delete'){if(confirm(`Delete “${p.name}”?`)){db.projects=db.projects.filter(x=>x!==p);save();render()}return}if(type==='accept'){p.worker=u.id;p.status='accepted'}if(type==='cancel'){p.status='cancelled'}if(type==='approve'){p.status='approved';p.approvedAt=new Date().toISOString()}if(type==='evidence'){let picker=document.querySelector('#evidence-picker');picker.value='';picker.onchange=async()=>{let files=[...picker.files];for(let file of files){let data=await new Promise(r=>{let fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file)});p.evidence.push(data)}p.status='submitted';save();render()};picker.click();return}save();render()}
render();
