const sb=window.supabase.createClient('https://olylrcpzcsioadhzlxdc.supabase.co','sb_publishable_OUsElPxxHSxf9hs1wH4jCA_GKgQKTZ3');
const el=s=>document.querySelector(s),clean=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(n)||0),cost=p=>Number(p.hours)*Number(p.hourly_rate);
let session,me,projects=[],workers=[],evidence={},selectedRole='user',signUp=false;
const isHost=()=>me?.role==='host',monthKey=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};

async function refresh(){
  session=(await sb.auth.getSession()).data.session;
  if(!session){me=null;draw();return}
  me=(await sb.from('profiles').select('*').eq('id',session.user.id).single()).data;
  if(!me){draw();return}
  projects=(await sb.from('projects').select('*').order('created_at',{ascending:false})).data||[];
  workers=isHost()?((await sb.from('profiles').select('*').eq('role','user').order('email')).data||[]):[];
  const rows=(await sb.from('project_evidence').select('*')).data||[]; evidence={};
  for(const row of rows){const signed=await sb.storage.from('evidence').createSignedUrl(row.storage_path,3600);if(signed.data?.signedUrl)(evidence[row.project_id]??=[]).push(signed.data.signedUrl)}
  draw();
}

function login(){return `<section class="auth"><div class="brand-panel"><div class="logo">cicadianai<span>·</span></div><div><p class="eyebrow">Secure project workspace</p><h1>Make every project count.</h1><p>Shared projects, evidence, and payment records—across every device.</p></div></div><div class="auth-box"><div class="auth-card"><p class="eyebrow">Welcome</p><h2>Cicadianai job list</h2><p class="muted">Choose how you want to enter the workspace.</p><div class="role-switch" aria-label="Account type"><button type="button" class="role" data-role="host">Host</button><button type="button" class="role active" data-role="user">User</button></div><form id="auth"><label>Email</label><input name="email" type="email" autocomplete="email" required><label>Password</label><input name="password" type="password" autocomplete="current-password" minlength="8" required><button class="btn" id="auth-submit">Sign in as user</button></form><button class="btn secondary" id="switch" type="button" style="margin-top:.7rem">Create a new account</button><p class="auth-note" id="role-note">Users can accept open or assigned projects and submit evidence.</p><div class="error" id="error" role="alert"></div></div></div></section>`}
function head(title,subtitle,action=''){return `<header class="topbar"><div><p class="eyebrow">${isHost()?'Host workspace':'User workspace'}</p><h1>${title}</h1><p>${subtitle}</p></div>${action}</header>`}
function projectCard(p){
  const mine=p.worker_id===session.user.id,canAccept=!isHost()&&p.status==='open'&&(!p.assigned_to||p.assigned_to===session.user.id),pics=(evidence[p.id]||[]).map(url=>`<a href="${url}" target="_blank" rel="noreferrer"><img src="${url}" alt="Submitted work evidence"></a>`).join('');let buttons='';
  if(isHost()&&p.status==='open')buttons=`<button class="btn small secondary" data-action="edit" data-id="${p.id}">Edit</button><button class="btn small danger" data-action="delete" data-id="${p.id}">Delete</button>`;
  if(isHost()&&p.status==='submitted')buttons=`<button class="btn small" data-action="approve" data-id="${p.id}">Approve & pay</button>`;
  if(isHost()&&p.status==='cancel_requested')buttons=`<button class="btn small danger" data-action="approve-cancel" data-id="${p.id}">Approve cancellation</button>`;
  if(canAccept)buttons=`<button class="btn small" data-action="accept" data-id="${p.id}">Accept project</button>`;
  if(!isHost()&&mine&&['accepted','submitted'].includes(p.status))buttons=`<button class="btn small secondary" data-action="proof" data-id="${p.id}">Add evidence</button><button class="btn small danger" data-action="cancel" data-id="${p.id}">Request cancellation</button>`;
  return `<article class="project"><div><h3>${clean(p.name)}</h3>${p.description?`<p class="project-description">${clean(p.description)}</p>`:''}<p><span class="badge">${clean(String(p.status||'open').replaceAll('_',' '))}</span>${p.hours} hours · ${cash(p.hourly_rate)}/hour · <strong>${cash(cost(p))}</strong>${p.deadline?` · Due ${clean(p.deadline)}`:''}</p>${pics?`<div class="evidence">${pics}</div>`:''}</div><div class="project-actions">${buttons}</div></article>`;
}
function dashboard(){
  const shown=isHost()?projects:projects.filter(p=>p.worker_id===session.user.id||(p.status==='open'&&(!p.assigned_to||p.assigned_to===session.user.id))),approved=shown.filter(p=>p.status==='approved').reduce((s,p)=>s+cost(p),0);
  return `${head(isHost()?'Project control':'Available projects',isHost()?'Create, assign, and approve work.':'Accept work, manage your jobs, and submit evidence.',isHost()?'<button class="btn" id="new">+ New project</button>':'')}<div class="stats"><article class="stat"><span class="eyebrow">Projects</span><b>${shown.length}</b></article><article class="stat"><span class="eyebrow">Open</span><b>${shown.filter(p=>p.status==='open').length}</b></article><article class="stat"><span class="eyebrow">For approval</span><b>${shown.filter(p=>p.status==='submitted').length}</b></article><article class="stat"><span class="eyebrow">Approved</span><b>${cash(approved)}</b></article></div><div class="project-list">${shown.map(projectCard).join('')||'<div class="empty">No projects available.</div>'}</div>`;
}
function paymentTable(list){return `<div class="ledger"><table><thead><tr><th>Project</th><th>Approved</th><th>Hours</th><th>Rate</th><th>Total</th></tr></thead><tbody>${list.map(p=>`<tr><td>${clean(p.name)}</td><td>${p.approved_at?new Date(p.approved_at).toLocaleDateString('en-GB'):'—'}</td><td>${p.hours}</td><td>${cash(p.hourly_rate)}</td><td><strong>${cash(cost(p))}</strong></td></tr>`).join('')||'<tr><td colspan="5">No approved payments yet.</td></tr>'}</tbody></table></div>`}
function chart(list){const now=new Date(),months=Array.from({length:12},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-11+i,1);return{key:monthKey(d),label:d.toLocaleDateString('en-GB',{month:'short'})}}),totals=months.map(m=>list.filter(p=>monthKey(p.approved_at||p.created_at)===m.key).reduce((s,p)=>s+cost(p),0)),max=Math.max(...totals,1);return `<div class="chart">${months.map((m,i)=>`<div class="bar" title="${m.label}: ${cash(totals[i])}"><span>${cash(totals[i])}</span><i style="height:${Math.max(3,totals[i]/max*150)}px"></i><small>${m.label}</small></div>`).join('')}</div>`}
function ledger(){const approved=projects.filter(p=>p.worker_id===session.user.id&&p.status==='approved'),total=approved.reduce((s,p)=>s+cost(p),0),key=monthKey(new Date()),monthly=approved.filter(p=>monthKey(p.approved_at||p.created_at)===key);return `${head('My earnings','Only your approved projects and payments are shown.')}<div class="stats"><article class="stat"><span class="eyebrow">Approved projects</span><b>${approved.length}</b></article><article class="stat"><span class="eyebrow">Total earned</span><b>${cash(total)}</b></article><article class="stat"><span class="eyebrow">This month</span><b>${cash(monthly.reduce((s,p)=>s+cost(p),0))}</b></article><article class="stat"><span class="eyebrow">Jobs this month</span><b>${monthly.length}</b></article></div><div class="section-head"><h2>Last 12 months</h2></div>${chart(approved)}<div class="section-head"><h2>Payment history</h2></div>${paymentTable(approved)}`}
function people(){const approved=projects.filter(p=>p.status==='approved'),key=monthKey(new Date()),month=approved.filter(p=>monthKey(p.approved_at||p.created_at)===key);return `${head('Users & earnings','A host-only overview of every registered user and their approved pay.')}<div class="stats"><article class="stat"><span class="eyebrow">Users</span><b>${workers.length}</b></article><article class="stat"><span class="eyebrow">Approved projects</span><b>${approved.length}</b></article><article class="stat"><span class="eyebrow">Total paid</span><b>${cash(approved.reduce((s,p)=>s+cost(p),0))}</b></article><article class="stat"><span class="eyebrow">Paid this month</span><b>${cash(month.reduce((s,p)=>s+cost(p),0))}</b></article></div><div class="ledger"><table><thead><tr><th>User</th><th>Approved projects</th><th>This month</th><th>Total earned</th></tr></thead><tbody>${workers.map(w=>{const all=approved.filter(p=>p.worker_id===w.id),recent=all.filter(p=>monthKey(p.approved_at||p.created_at)===key);return `<tr><td>${clean(w.email)}</td><td>${all.length}</td><td>${cash(recent.reduce((s,p)=>s+cost(p),0))}</td><td><strong>${cash(all.reduce((s,p)=>s+cost(p),0))}</strong></td></tr>`}).join('')||'<tr><td colspan="4">No user accounts yet.</td></tr>'}</tbody></table></div>`}
function app(){const wanted=location.hash.slice(1),page=wanted==='earnings'?'earnings':wanted==='users'&&isHost()?'users':'projects';return `<section class="shell"><aside class="sidebar"><div class="logo">cicadianai<span>·</span></div><nav class="nav"><button data-page="projects" class="${page==='projects'?'active':''}">Projects</button>${isHost()?`<button data-page="users" class="${page==='users'?'active':''}">Users & earnings</button>`:`<button data-page="earnings" class="${page==='earnings'?'active':''}">My earnings</button>`}</nav><div class="account"><strong>${clean(me.email)}</strong><span>${isHost()?'Host':'User'}</span><button id="out" class="btn small secondary">Sign out</button></div></aside><main class="content">${page==='users'?people():page==='earnings'?ledger():dashboard()}</main></section><div id="modal-root"></div>`}
function draw(){
  if(!me)signUp=false;
  el('#app').innerHTML=me?app():login();
  bind();
}

function projectForm(p){
  if(!isHost())return;
  el('#modal-root').innerHTML=`<div class="modal-wrap"><form class="modal" id="project-form"><h2>${p?'Edit':'New'} project</h2><label>Project name</label><input name="name" value="${clean(p?.name)}" required><label>Description</label><textarea name="description" placeholder="Describe the work, requirements, and expected result">${clean(p?.description)}</textarea><div class="form-grid"><div><label>Hours</label><input name="hours" type="number" min="0.5" step="0.5" value="${p?.hours||''}" required></div><div><label>Pay per hour (£)</label><input name="hourly_rate" type="number" min="0" step="0.01" value="${p?.hourly_rate||''}" required></div><div><label>Deadline (optional)</label><input name="deadline" type="date" value="${p?.deadline||''}"></div><div><label>Assign to</label><select name="assigned_to"><option value="">Anyone can accept</option>${workers.map(w=>`<option value="${w.id}" ${p?.assigned_to===w.id?'selected':''}>${clean(w.email)}</option>`).join('')}</select></div></div><p class="details" id="cost-preview">Project cost: <strong>${cash(p?cost(p):0)}</strong></p><div class="form-actions"><button type="button" class="btn secondary" id="close">Cancel</button><button class="btn">Save project</button></div></form></div>`;
  const form=el('#project-form'),updateCost=()=>el('#cost-preview').innerHTML=`Project cost: <strong>${cash(Number(form.hours.value)*Number(form.hourly_rate.value))}</strong>`;
  form.hours.oninput=updateCost;form.hourly_rate.oninput=updateCost;el('#close').onclick=()=>el('.modal-wrap').remove();
  form.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));d.hours=Number(d.hours);d.hourly_rate=Number(d.hourly_rate);d.assigned_to=d.assigned_to||null;d.allow_anyone=!d.assigned_to;d.deadline=d.deadline||null;d.description=d.description.trim()||null;d.created_by=session.user.id;const result=p?await sb.from('projects').update(d).eq('id',p.id):await sb.from('projects').insert(d);if(result.error){alert(result.error.message);return}await refresh()};
}
function setAuthCopy(){const name=selectedRole==='host'?'host':'user';el('#auth-submit').textContent=signUp?`Create ${name} account`:`Sign in as ${name}`;el('#switch').textContent=signUp?'I already have an account':'Create a new account';el('#role-note').textContent=selectedRole==='host'?'Host access is granted only to authorised host accounts.':'Users can accept open or assigned projects and submit evidence.';document.querySelectorAll('.role').forEach(b=>b.classList.toggle('active',b.dataset.role===selectedRole))}
function bind(){
  if(!me){document.querySelectorAll('.role').forEach(b=>b.onclick=()=>{selectedRole=b.dataset.role;setAuthCopy()});el('#switch').onclick=()=>{signUp=!signUp;setAuthCopy()};el('#auth').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));el('#error').textContent='';const result=signUp?await sb.auth.signUp({email:d.email,password:d.password,options:{emailRedirectTo:location.href,data:{requested_role:selectedRole}}}):await sb.auth.signInWithPassword({email:d.email,password:d.password});if(result.error){el('#error').textContent=result.error.message;return}if(signUp&&!result.data.session){el('#error').textContent='Check your email to confirm the account, then sign in.';return}if(!signUp){const profile=await sb.from('profiles').select('role').eq('id',result.data.user.id).single();if(profile.data?.role!==selectedRole){await sb.auth.signOut();el('#error').textContent=`This account is registered as ${profile.data?.role==='host'?'a host':'a user'}. Choose the correct login option.`;return}}await refresh()};return}
  el('#out').onclick=()=>sb.auth.signOut();el('#new')?.addEventListener('click',()=>projectForm());document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.page==='projects'?'':b.dataset.page;draw()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>projectAction(b.dataset.action,b.dataset.id));
}
async function projectAction(action,id){const p=projects.find(x=>x.id===id);if(action==='edit')return projectForm(p);if(action==='delete'&&confirm('Delete this project?'))await sb.from('projects').delete().eq('id',id);if(action==='accept')await sb.rpc('accept_project',{p_project_id:id});if(action==='cancel')await sb.rpc('request_cancellation',{p_project_id:id});if(action==='approve')await sb.from('projects').update({status:'approved',approved_at:new Date().toISOString()}).eq('id',id);if(action==='approve-cancel')await sb.from('projects').update({status:'open',worker_id:null}).eq('id',id);if(action==='proof'){const picker=el('#evidence-picker');picker.value='';picker.onchange=async()=>{for(const file of picker.files){const name=file.name.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${id}/${session.user.id}/${Date.now()}-${name}`,upload=await sb.storage.from('evidence').upload(path,file);if(upload.error){alert(upload.error.message);return}await sb.from('project_evidence').insert({project_id:id,submitted_by:session.user.id,storage_path:path})}await sb.rpc('mark_submitted',{p_project_id:id});await refresh()};picker.click();return}await refresh()}
window.addEventListener('hashchange',()=>me&&draw());sb.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
